### ISSUE TITLE
pre-trained AudioSep-DP models

### ISSUE THREAD

**Issue by visionchan** [apple-yinhan/TQ-SED#1]
Where could I get your pre-trained AudioSep-DP models, I did not find the hyperlink of it.

Please tell me, thanks!

**Comment by apple-yinhan** [comment]
sorry, i forgot🤣, i'll upload soon !

**Comment by apple-yinhan** [comment]
I've already uploaded the pre-trained AudioSep-DP on zenodo, please refer to the Readme

**Comment by visionchan** [comment]
> I've already uploaded the pre-trained AudioSep-DP on zenodo, please refer to the Readme

Nice! I got it.
